
OCAMLFLAGS = 
LIBS = labltk lablgl str img png_img
OLIBS = togl
INCDIRS = /usr/lib/ocaml/labltk /usr/lib/ocaml/lablGL /usr/lib/ocaml/camlimages

SOURCES = objtype.mli object.mli object.ml test.mli test.ml

RESULT = test

-include OcamlMakefile

all:	byte-code

